// This file is auto-generated by the `update-kc-gen` command. Do not edit it manually.
// Hash: 242ac8ab47635fbbe5102aa0474a5ab64132e6723e6a7e9eed78d15d57751ab3

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

import { lazy, Suspense, type ReactNode } from "react";

export type ThemeName = "acme-theme";

export const themeNames: ThemeName[] = ["acme-theme"];

export type KcEnvName =
    | "SHADECN_THEME_LOGO_URL"
    | "SHADECN_THEME_APP_NAME"
    | "SHADECN_THEME_LAYOUT"
    | "SHADECN_THEME_SIDE_IMAGE_URL";

export const kcEnvNames: KcEnvName[] = [
    "SHADECN_THEME_LOGO_URL",
    "SHADECN_THEME_APP_NAME",
    "SHADECN_THEME_LAYOUT",
    "SHADECN_THEME_SIDE_IMAGE_URL"
];

export const kcEnvDefaults: Record<KcEnvName, string> = {
    SHADECN_THEME_LOGO_URL: "",
    SHADECN_THEME_APP_NAME: "Acme Inc.",
    SHADECN_THEME_LAYOUT: "image-aside",
    SHADECN_THEME_SIDE_IMAGE_URL: ""
};

/**
 * NOTE: Do not import this type except maybe in your entrypoint.
 * If you need to import the KcContext import it either from src/login/KcContext.ts or src/account/KcContext.ts.
 * Depending on the theme type you are working on.
 */
export type KcContext = import("./login/KcContext").KcContext;

declare global {
    interface Window {
        kcContext?: KcContext;
    }
}

export const KcLoginPage = lazy(() => import("./login/KcPage"));

export function KcPage(props: { kcContext: KcContext; fallback?: ReactNode }) {
    const { kcContext, fallback } = props;
    return (
        <Suspense fallback={fallback}>
            {(() => {
                switch (kcContext.themeType) {
                    case "login":
                        return <KcLoginPage kcContext={kcContext} />;
                }
            })()}
        </Suspense>
    );
}

// NOTE: This is exported here only because in Webpack environnement it works differently
export const BASE_URL = import.meta.env.BASE_URL;

// NOTE: This is only exported here because you're supposed to import type from different packages
// Depending of if you are using Vite, Webpack, ect...
export type { Meta, StoryObj } from "@storybook/react-vite";
